In [3]:
import pandas as pd 
import numpy as np  
import matplotlib.pyplot as plt  
import seaborn as sns

%matplotlib inline

In [4]:
teis_df = pd.read_excel (r'C:\Users\jubs1\Documents\NSS\python\projects\teis_project-ursula\data\TEIS Referral Data for NSS Compiled Monthly.xlsx')
teis_df.to_csv (r'C:\Users\jubs1\Documents\NSS\python\projects\teis_project-ursula\data\TEIS Referral Data for NSS Compiled Monthly.xlsx', index = None, header=True)

In [7]:
teis_df

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,2016-07-01,...,1,2016,1,NaN,NaN,2017-08-09,NaN,1,Qtr 1,NaN
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2016-07-31,1.0,1,Qtr 1,NaN
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,2016-07-20,...,1,2016,1,NaN,NaN,2019-02-05,NaN,1,Qtr 1,NaN
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,2016-07-22,...,1,2016,1,NaN,NaN,2018-12-06,NaN,1,Qtr 1,NaN
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,2016-07-18,...,1,2016,1,NaN,NaN,2018-04-18,NaN,1,Qtr 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,2022-05-26,...,1,2021,1,NaN,NaN,2024-04-07,NaN,4,Qtr 4,NaN
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,2022-05-23,...,1,2021,1,NaN,NaN,2025-03-13,NaN,4,Qtr 4,NaN
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,2022-05-18,...,1,2021,1,NaN,NaN,2025-01-05,NaN,4,Qtr 4,NaN
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,2022-05-11,...,1,2021,1,NaN,NaN,2023-09-12,NaN,4,Qtr 4,NaN
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,2022-05-27,...,1,2021,1,NaN,NaN,2025-02-08,NaN,4,Qtr 4,NaN

In [11]:
teis_df = teis_df.rename(columns = {'Child ID' : 'child id', 'Fiscal Year.1': 'fiscal_year1', 'Notification/ Referral Date': 'referral_date', 'Country SES': 'county_ses', 'Referral Source Type Name': 'referral_source', 'Initial Eligibility Date': 'success_date' })
teis_df

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,2016-07-01,...,1,2016,1,NaN,NaN,2017-08-09,NaN,1,Qtr 1,NaN
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2016-07-31,1.0,1,Qtr 1,NaN
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,2016-07-20,...,1,2016,1,NaN,NaN,2019-02-05,NaN,1,Qtr 1,NaN
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,2016-07-22,...,1,2016,1,NaN,NaN,2018-12-06,NaN,1,Qtr 1,NaN
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,2016-07-18,...,1,2016,1,NaN,NaN,2018-04-18,NaN,1,Qtr 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,2022-05-26,...,1,2021,1,NaN,NaN,2024-04-07,NaN,4,Qtr 4,NaN
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,2022-05-23,...,1,2021,1,NaN,NaN,2025-03-13,NaN,4,Qtr 4,NaN
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,2022-05-18,...,1,2021,1,NaN,NaN,2025-01-05,NaN,4,Qtr 4,NaN
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,2022-05-11,...,1,2021,1,NaN,NaN,2023-09-12,NaN,4,Qtr 4,NaN
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,2022-05-27,...,1,2021,1,NaN,NaN,2025-02-08,NaN,4,Qtr 4,NaN

In [13]:
teis_df.duplicated(subset=['child id']).sum()

18306

In [14]:
teis_df.sort_values(by = 'child id', ascending = True)
teis_df

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,2016-07-01,...,1,2016,1,NaN,NaN,2017-08-09,NaN,1,Qtr 1,NaN
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2016-07-31,1.0,1,Qtr 1,NaN
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,2016-07-20,...,1,2016,1,NaN,NaN,2019-02-05,NaN,1,Qtr 1,NaN
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,2016-07-22,...,1,2016,1,NaN,NaN,2018-12-06,NaN,1,Qtr 1,NaN
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,2016-07-18,...,1,2016,1,NaN,NaN,2018-04-18,NaN,1,Qtr 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,2022-05-26,...,1,2021,1,NaN,NaN,2024-04-07,NaN,4,Qtr 4,NaN
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,2022-05-23,...,1,2021,1,NaN,NaN,2025-03-13,NaN,4,Qtr 4,NaN
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,2022-05-18,...,1,2021,1,NaN,NaN,2025-01-05,NaN,4,Qtr 4,NaN
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,2022-05-11,...,1,2021,1,NaN,NaN,2023-09-12,NaN,4,Qtr 4,NaN
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,2022-05-27,...,1,2021,1,NaN,NaN,2025-02-08,NaN,4,Qtr 4,NaN

In [15]:
dups_df = teis_df.loc[teis_df.duplicated(subset='child id', keep=False)]
dups_df

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,2016-07-20,...,1,2016,1,NaN,NaN,2019-02-05,NaN,1,Qtr 1,NaN
6,GN,404087,2014-10-29,Davidson,Competitive,Notification,I,Mary Jane Ratliff,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2017-10-29,NaN,1,Qtr 1,NaN
7,GN,402274,2015-12-10,Montgomery,Transitional,Eligibility,I,Tina Regenwether,2016-07-01,2016-07-07,...,1,2016,1,NaN,NaN,2018-12-10,NaN,1,Qtr 1,NaN
11,MD,404074,2016-05-23,Shelby,Transitional,Notification,I,Helen Shipp,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2019-05-23,NaN,1,Qtr 1,NaN
14,MD,404081,2016-04-23,Shelby,Transitional,Notification,I,JoAnn Hinkle-DA,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2019-04-23,NaN,1,Qtr 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113225,UC,508343,2021-06-14,Putnam,Transitional,Eligibility,A,A.J. Cowan,2022-05-25,NaT,...,1,2021,1,NaN,NaN,2024-06-14,NaN,4,Qtr 4,NaN
113235,UC,512956,2019-10-17,Sumner,Competitive,Eligibility,A,Taylor Lee,2022-05-09,2022-05-27,...,1,2021,1,NaN,NaN,2022-10-17,NaN,4,Qtr 4,NaN
113241,UC,497416,2021-01-08,Warren,At-Risk,Notification,I,Sherry Roberts-DS,2022-05-10,NaT,...,1,2021,1,NaN,NaN,2024-01-08,NaN,4,Qtr 4,NaN
113246,UC,527351,2021-07-08,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-10,2022-05-17,...,1,2021,1,NaN,NaN,2024-07-08,NaN,4,Qtr 4,NaN
113248,UC,516784,2020-09-01,Warren,At-Risk,Notification,I,Sherry Roberts-DS,2022-05-04,NaT,...,1,2021,1,NaN,NaN,2023-09-01,NaN,4,Qtr 4,NaN

In [16]:
dups_df.sort_values(by = "child id")

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
8326,ET,360966,2014-01-18,Monroe,At-Risk,Notification,I,Cassidy Wilbanks,2017-01-12,NaT,...,1,2016,1,NaN,NaN,2017-01-18,1.0,3,Qtr 3,NaN
6007,ET,360966,2014-01-18,Monroe,At-Risk,Notification,I,Leslie Milligan,2016-11-10,NaT,...,1,2016,1,NaN,NaN,2017-01-18,1.0,2,Qtr 2,NaN
5441,ET,361021,2014-02-17,Anderson,Transitional,Notification,A,Cathy Taylor,2016-10-28,NaT,...,1,2016,1,NaN,NaN,2017-02-17,NaN,2,Qtr 2,NaN
6658,ET,361021,2014-02-17,Anderson,Transitional,IFSP,A,Cathy Taylor,2016-11-29,2016-11-29,...,1,2016,1,NaN,NaN,2017-02-17,1.0,2,Qtr 2,NaN
5189,GN,361038,2013-12-25,Wilson,Competitive,Eligibility,A,Patricia Lyle,2016-10-24,NaT,...,1,2016,1,NaN,NaN,2016-12-25,1.0,2,Qtr 2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111573,ET,527636,2020-05-01,Blount,Transitional,Eligibility,I,Signal Centers-EEA,2022-05-27,2022-05-27,...,1,2021,1,NaN,NaN,2023-05-01,NaN,4,Qtr 4,NaN
110585,MD,527691,2021-12-23,Shelby,Transitional,Notification,A,Jasmine Douglass,2022-04-28,NaT,...,1,2021,1,NaN,NaN,2024-12-23,NaN,4,Qtr 4,NaN
112414,MD,527691,2021-12-23,Shelby,Transitional,Notification,A,Jasmine Douglass,2022-05-20,NaT,...,1,2021,1,NaN,NaN,2024-12-23,NaN,4,Qtr 4,NaN
111752,FT,527751,2021-10-23,Sullivan,Transitional,Notification,I,Rebecca Fletcher - Admin,2022-05-17,NaT,...,1,2021,1,NaN,NaN,2024-10-23,NaN,4,Qtr 4,NaN
109913,FT,527751,2021-10-23,Sullivan,Transitional,Notification,I,Alicia Taylor - Admin,2022-04-28,NaT,...,1,2021,1,NaN,NaN,2024-10-23,NaN,4,Qtr 4,NaN

In [17]:
dupscount_df = dups_df.loc[dups_df.duplicated(subset='child id', keep='first')]
dupscount_df

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
1739,GN,404546,2015-06-28,Davidson,Competitive,IFSP,A,Shawn Jones,2016-08-10,2016-08-10,...,1,2016,1,NaN,NaN,2018-06-28,NaN,1,Qtr 1,NaN
1751,MD,404524,2014-01-09,Shelby,Transitional,Evaluation,A,Karen Hunter,2016-08-10,2016-08-10,...,1,2016,1,NaN,NaN,2017-01-09,NaN,1,Qtr 1,NaN
1775,ET,404319,2016-04-17,Anderson,Transitional,Eligibility,I,Cassidy Wilbanks,2016-08-11,2016-08-23,...,1,2016,1,NaN,NaN,2019-04-17,NaN,1,Qtr 1,NaN
1819,SC,404136,2016-03-10,Rutherford,Competitive,IFSP,A,Christina Shafer,2016-08-11,2016-08-11,...,1,2016,1,NaN,NaN,2019-03-10,NaN,1,Qtr 1,NaN
1836,ET,392203,2014-10-01,Roane,Transitional,Eligibility,A,Theresa Bridges-East,2016-08-12,2016-08-15,...,1,2016,1,NaN,NaN,2017-10-01,NaN,1,Qtr 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113225,UC,508343,2021-06-14,Putnam,Transitional,Eligibility,A,A.J. Cowan,2022-05-25,NaT,...,1,2021,1,NaN,NaN,2024-06-14,NaN,4,Qtr 4,NaN
113235,UC,512956,2019-10-17,Sumner,Competitive,Eligibility,A,Taylor Lee,2022-05-09,2022-05-27,...,1,2021,1,NaN,NaN,2022-10-17,NaN,4,Qtr 4,NaN
113241,UC,497416,2021-01-08,Warren,At-Risk,Notification,I,Sherry Roberts-DS,2022-05-10,NaT,...,1,2021,1,NaN,NaN,2024-01-08,NaN,4,Qtr 4,NaN
113246,UC,527351,2021-07-08,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-10,2022-05-17,...,1,2021,1,NaN,NaN,2024-07-08,NaN,4,Qtr 4,NaN
113248,UC,516784,2020-09-01,Warren,At-Risk,Notification,I,Sherry Roberts-DS,2022-05-04,NaT,...,1,2021,1,NaN,NaN,2023-09-01,NaN,4,Qtr 4,NaN

In [19]:
dupscount_df.sort_values(by = "child id")

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
8326,ET,360966,2014-01-18,Monroe,At-Risk,Notification,I,Cassidy Wilbanks,2017-01-12,NaT,...,1,2016,1,NaN,NaN,2017-01-18,1.0,3,Qtr 3,NaN
6658,ET,361021,2014-02-17,Anderson,Transitional,IFSP,A,Cathy Taylor,2016-11-29,2016-11-29,...,1,2016,1,NaN,NaN,2017-02-17,1.0,2,Qtr 2,NaN
5189,GN,361038,2013-12-25,Wilson,Competitive,Eligibility,A,Patricia Lyle,2016-10-24,NaT,...,1,2016,1,NaN,NaN,2016-12-25,1.0,2,Qtr 2,NaN
5446,ET,361040,2014-01-22,Roane,Transitional,IFSP,A,Brandi Mohr,2016-10-28,2016-10-28,...,1,2016,1,NaN,NaN,2017-01-22,1.0,2,Qtr 2,NaN
9302,SC,363098,2014-04-07,Bedford,Transitional,IFSP,A,Tina Durham,2017-01-31,NaT,...,1,2016,1,NaN,NaN,2017-04-07,1.0,3,Qtr 3,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113189,UC,527583,2019-09-17,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-18,2022-05-25,...,1,2021,1,NaN,NaN,2022-09-17,NaN,4,Qtr 4,NaN
111618,ET,527603,2021-07-08,Union,At-Risk,Eligibility,A,Shawnna Carpenter,2022-05-12,2022-05-25,...,1,2021,1,NaN,NaN,2024-07-08,NaN,4,Qtr 4,NaN
111573,ET,527636,2020-05-01,Blount,Transitional,Eligibility,I,Signal Centers-EEA,2022-05-27,2022-05-27,...,1,2021,1,NaN,NaN,2023-05-01,NaN,4,Qtr 4,NaN
112414,MD,527691,2021-12-23,Shelby,Transitional,Notification,A,Jasmine Douglass,2022-05-20,NaT,...,1,2021,1,NaN,NaN,2024-12-23,NaN,4,Qtr 4,NaN
111752,FT,527751,2021-10-23,Sullivan,Transitional,Notification,I,Rebecca Fletcher - Admin,2022-05-17,NaT,...,1,2021,1,NaN,NaN,2024-10-23,NaN,4,Qtr 4,NaN

In [29]:
teiscount_df = teis_df.drop_duplicates(subset = ['child id'], keep = False)
teiscount_df

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,2016-07-01,...,1,2016,1,NaN,NaN,2017-08-09,NaN,1,Qtr 1,NaN
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,NaT,...,1,2016,1,NaN,NaN,2016-07-31,1.0,1,Qtr 1,NaN
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,2016-07-22,...,1,2016,1,NaN,NaN,2018-12-06,NaN,1,Qtr 1,NaN
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,2016-07-18,...,1,2016,1,NaN,NaN,2018-04-18,NaN,1,Qtr 1,NaN
5,GN,401584,2016-03-27,Montgomery,Transitional,Eligibility,A,Tracey Hardiman,2016-07-01,2016-07-05,...,1,2016,1,NaN,NaN,2019-03-27,NaN,1,Qtr 1,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,2022-05-26,...,1,2021,1,NaN,NaN,2024-04-07,NaN,4,Qtr 4,NaN
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,2022-05-23,...,1,2021,1,NaN,NaN,2025-03-13,NaN,4,Qtr 4,NaN
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,2022-05-18,...,1,2021,1,NaN,NaN,2025-01-05,NaN,4,Qtr 4,NaN
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,2022-05-11,...,1,2021,1,NaN,NaN,2023-09-12,NaN,4,Qtr 4,NaN
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,2022-05-27,...,1,2021,1,NaN,NaN,2025-02-08,NaN,4,Qtr 4,NaN

In [24]:
teiscount_df.sort_values(by = "child id")

,POE,child id,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
8326,ET,360966,2014-01-18,Monroe,At-Risk,Notification,I,Cassidy Wilbanks,2017-01-12,NaT,...,1,2016,1,NaN,NaN,2017-01-18,1.0,3,Qtr 3,NaN
6007,ET,360966,2014-01-18,Monroe,At-Risk,Notification,I,Leslie Milligan,2016-11-10,NaT,...,1,2016,1,NaN,NaN,2017-01-18,1.0,2,Qtr 2,NaN
5441,ET,361021,2014-02-17,Anderson,Transitional,Notification,A,Cathy Taylor,2016-10-28,NaT,...,1,2016,1,NaN,NaN,2017-02-17,NaN,2,Qtr 2,NaN
6658,ET,361021,2014-02-17,Anderson,Transitional,IFSP,A,Cathy Taylor,2016-11-29,2016-11-29,...,1,2016,1,NaN,NaN,2017-02-17,1.0,2,Qtr 2,NaN
5189,GN,361038,2013-12-25,Wilson,Competitive,Eligibility,A,Patricia Lyle,2016-10-24,NaT,...,1,2016,1,NaN,NaN,2016-12-25,1.0,2,Qtr 2,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111573,ET,527636,2020-05-01,Blount,Transitional,Eligibility,I,Signal Centers-EEA,2022-05-27,2022-05-27,...,1,2021,1,NaN,NaN,2023-05-01,NaN,4,Qtr 4,NaN
110585,MD,527691,2021-12-23,Shelby,Transitional,Notification,A,Jasmine Douglass,2022-04-28,NaT,...,1,2021,1,NaN,NaN,2024-12-23,NaN,4,Qtr 4,NaN
112414,MD,527691,2021-12-23,Shelby,Transitional,Notification,A,Jasmine Douglass,2022-05-20,NaT,...,1,2021,1,NaN,NaN,2024-12-23,NaN,4,Qtr 4,NaN
111752,FT,527751,2021-10-23,Sullivan,Transitional,Notification,I,Rebecca Fletcher - Admin,2022-05-17,NaT,...,1,2021,1,NaN,NaN,2024-10-23,NaN,4,Qtr 4,NaN
109913,FT,527751,2021-10-23,Sullivan,Transitional,Notification,I,Alicia Taylor - Admin,2022-04-28,NaT,...,1,2021,1,NaN,NaN,2024-10-23,NaN,4,Qtr 4,NaN

In [44]:
dupsRcount = dups_df.duplicated(subset=['child id']).sum()

In [43]:
dupsRcount

18306

AttributeError: 'numpy.int64' object has no attribute 'columns'