In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import datetime

%matplotlib inline

In [2]:
monthly_df = pd.read_excel('../data/TEIS_Referral_Data_for_NSS_Compiled_Monthly.xlsx')
monthly_df.columns = map(str.lower, monthly_df.columns)
monthly_df.columns = monthly_df.columns.str.replace(' ', '_')
monthly_df['exit_date'] = pd.to_datetime(monthly_df['exit_date'], errors = 'coerce')
monthly_df['initial_ifsp_date'] = pd.to_datetime(monthly_df['initial_ifsp_date'], errors='coerce')
monthly_df = monthly_df.drop(columns = ['referral_source_category', '_qtr_', 'qtr', 'late_referral', '2013_child_count', '2012_child_count', 'child_count', 'service_coordinator_counter',  'eligibility_count', 'evaluation_count', 'notification_month', 'tenn_region', 'latest_ifsp_date', 'initial_eligibility', 'initial_eligibility_date', 'parent_consent_date'])
monthly_df['successful'] = np.where(monthly_df['initial_ifsp_date'].isnull(), ("not_successful"), ("successful"))
monthly_df

,poe,child_id,dob,county_name,county_ses,child_phase,active,service_coordinator,notification/_referral_date,referral_source_type_name,initial_ifsp_date,exit_reason,exit_date,fiscal_year,referral_count,ifsp_count,fiscal_year.1,third_dob,successful
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,Foster Parent,NaT,NaN,NaT,2016-2017,1,NaN,2016,2017-08-09,not_successful
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,DCS,NaT,Referral less than 45 days,2016-07-01,2016-2017,1,NaN,2016,2016-07-31,not_successful
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,DCS,NaT,NaN,NaT,2016-2017,1,NaN,2016,2019-02-05,not_successful
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,PCP,2016-08-10,NaN,NaT,2016-2017,1,1.0,2016,2018-12-06,successful
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,Parent,2016-07-28,NaN,NaT,2016-2017,1,1.0,2016,2018-04-18,successful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,Parent,NaT,NaN,NaT,2021-2022,1,NaN,2021,2024-04-07,not_successful
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,Hospital,2022-06-14,NaN,NaT,2021-2022,1,1.0,2021,2025-03-13,successful
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,Parent,NaT,NaN,NaT,2021-2022,1,NaN,2021,2025-01-05,not_successful
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,PCP,2022-05-31,NaN,NaT,2021-2022,1,1.0,2021,2023-09-12,successful
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,Parent,NaT,NaN,NaT,2021-2022,1,NaN,2021,2025-02-08,not_successful

In [3]:
july_df = pd.read_excel('../data/TEIS_Referral_Data_for_Nss_pulled_7-1-22.xlsx')
july_df.columns = map(str.lower, july_df.columns)
july_df.columns = july_df.columns.str.replace(' ', '_')
july_df['successful'] = np.where(july_df['initial_ifsp_date'].isnull(), ("not_successful"), ("successful"))

july_df

,poe,child_id,dob,county_name,county_ses_,child_phase,active,service_coordinator,notification_date,parent_consent_date,referral_source_type_name,initial_eligibility,initial_eligibility_date,initial_ifsp_date,latest_ifsp_date,exit_reason,exit_date,successful
0,ET,411812,2016-12-14,Blount,Transitional,Notification,I,Charity Decker,2016-12-16,NaT,DCS,NaN,NaT,NaT,NaT,Unable to contact,2016-12-29,not_successful
1,ET,417398,2015-04-06,Knox,Transitional,Eligibility,I,Jackie Campbell,2017-04-24,2017-05-02,Parent,Ineligible,2017-05-16,NaT,NaT,Ineligible for Part C,2017-05-16,not_successful
2,ET,419400,2016-03-04,Roane,Transitional,Notification,I,Kelly Brackney,2017-06-06,NaT,DCS,NaN,NaT,NaT,NaT,Parent decline,2017-06-30,not_successful
3,ET,397571,2015-05-11,Knox,Transitional,Eligibility,I,Wendy Burton,2017-05-24,2017-06-13,Other,Ineligible,2017-06-16,NaT,NaT,Ineligible for Part C,2017-06-16,not_successful
4,ET,404648,2015-09-23,Knox,Transitional,IFSP,I,Sarah Scott,2016-07-18,2016-07-28,Other,Eligible,2016-08-01,2016-08-16,2018-07-24,618 - Part B eligibility not determined,2018-09-21,successful
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96575,UC,519094,2020-04-10,Macon,Transitional,Eligibility,I,Sherry Roberts-DS,2022-01-12,2022-01-19,PCP,Ineligible,2022-01-31,NaT,NaT,Ineligible for Part C,2022-01-31,not_successful
96576,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,2022-05-11,PCP,Eligible,2022-05-23,2022-05-31,2022-05-31,NaN,NaT,successful
96577,UC,525460,2019-08-27,Sumner,Competitive,Notification,I,Sherry Roberts-DS,2022-03-29,NaT,PCP,NaN,NaT,NaT,NaT,Unable to contact,2022-04-11,not_successful
96578,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,2022-05-27,Parent,NaN,NaT,NaT,NaT,NaN,NaT,not_successful
96579,UC,514216,2021-02-04,Sumner,Competitive,IFSP,I,Dawn Reed,2021-11-05,2021-11-10,PCP,Eligible,2021-12-01,2021-12-07,2021-12-07,618 - Parent withdraw,2022-02-10,successful

### Some areas of potential concern are POEs having a low proportion of referrals, a high average age of referrals, a low percent of total referrals resulting in an IFSP or a lower percent of eligible referrals resulting in an IFSP. How do POEs compare on these metrics, and which POEs are of concern on the basis of one or more of the listed criteria?Â¶

# I answered these using the monthly dataset, but did not drop duplicates or unsuccessful referrals

## FIrst: what is the average age of children at time of referral per POE?

In [4]:
# add age column, age calculated in months from DOB to referral date
monthly_df = monthly_df.rename(columns = {'notification/_referral_date':'referral_date'})
monthly_df['birth_year'] = monthly_df['dob'].dt.year
monthly_df['birth_month'] = monthly_df['dob'].dt.month
monthly_df['referral_year'] = monthly_df['referral_date'].dt.year
monthly_df['referral_month'] = monthly_df['referral_date'].dt.month
monthly_df

,poe,child_id,dob,county_name,county_ses,child_phase,active,service_coordinator,referral_date,referral_source_type_name,...,fiscal_year,referral_count,ifsp_count,fiscal_year.1,third_dob,successful,birth_year,birth_month,referral_year,referral_month
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,Foster Parent,...,2016-2017,1,NaN,2016,2017-08-09,not_successful,2014,8,2016,7
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,DCS,...,2016-2017,1,NaN,2016,2016-07-31,not_successful,2013,7,2016,7
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,DCS,...,2016-2017,1,NaN,2016,2019-02-05,not_successful,2016,2,2016,7
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,PCP,...,2016-2017,1,1.0,2016,2018-12-06,successful,2015,12,2016,7
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,Parent,...,2016-2017,1,1.0,2016,2018-04-18,successful,2015,4,2016,7
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,Parent,...,2021-2022,1,NaN,2021,2024-04-07,not_successful,2021,4,2022,5
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,Hospital,...,2021-2022,1,1.0,2021,2025-03-13,successful,2022,3,2022,5
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,Parent,...,2021-2022,1,NaN,2021,2025-01-05,not_successful,2022,1,2022,5
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,PCP,...,2021-2022,1,1.0,2021,2023-09-12,successful,2020,9,2022,5
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,Parent,...,2021-2022,1,NaN,2021,2025-02-08,not_successful,2022,2,2022,5

In [5]:
#add age at referral column
monthly_df['age_at_referral_in_months'] = (monthly_df.referral_year - monthly_df.birth_year)*12 + (monthly_df.referral_month - monthly_df.birth_month)

In [8]:
referral_age = monthly_df[['child_id', 'poe', 'dob', 'referral_date', 'age_at_referral_in_months', 'county_ses', 'referral_source_type_name']]
referral_age.sort_values(by = 'child_id')

,child_id,poe,dob,referral_date,age_at_referral_in_months,county_ses,referral_source_type_name
25415,104085,GN,2007-07-07,2018-01-20,126,Competitive,DCS
2092,350065,UC,2013-10-15,2016-08-17,34,At-Risk,PCP
437,351755,NW,2013-11-13,2016-07-12,32,Transitional,Parent
3369,353800,FT,2013-10-01,2016-09-14,35,At-Risk,Parent
1552,353805,UC,2013-12-04,2016-08-05,32,Transitional,Dept. of Health
...,...,...,...,...,...,...,...
113190,529587,UC,2022-03-15,2022-05-31,2,Competitive,Other
112947,529597,SE,2020-04-10,2022-05-31,25,Transitional,PCP
112949,529599,SE,2019-08-23,2022-05-31,33,Transitional,Hospital
111729,529606,FT,2021-06-29,2022-05-31,11,Transitional,Parent
111777,529609,FT,2020-05-13,2022-05-31,24,Transitional,PCP

In [9]:
#drop referrals that were referred after 3rd brthday (36 months)
referral_age = referral_age[referral_age.age_at_referral_in_months <= 36]

In [10]:
referral_age

,child_id,poe,dob,referral_date,age_at_referral_in_months,county_ses,referral_source_type_name
0,403339,ET,2014-08-09,2016-07-01,23,Transitional,Foster Parent
1,404085,FT,2013-07-31,2016-07-01,36,At-Risk,DCS
2,403623,FT,2016-02-05,2016-07-01,5,Transitional,DCS
3,404157,FT,2015-12-06,2016-07-01,7,Transitional,PCP
4,404154,FT,2015-04-18,2016-07-01,15,At-Risk,Parent
...,...,...,...,...,...,...,...
113251,528759,UC,2021-04-07,2022-05-16,13,Competitive,Parent
113252,528534,UC,2022-03-13,2022-05-11,2,Competitive,Hospital
113253,528430,UC,2022-01-05,2022-05-10,4,Transitional,Parent
113254,528253,UC,2020-09-12,2022-05-06,20,Competitive,PCP
113255,528535,UC,2022-02-08,2022-05-11,3,Transitional,Parent

In [11]:
#subset df for aggregation
age_by_poe = referral_age[['poe', 'age_at_referral_in_months']]

### avg age in months at time of referral for each POE

In [12]:

age_by_poe.groupby('poe').mean()

     age_at_referral_in_months
poe
ET                   14.824870
FT                   13.961404
GN                   16.467525
MD                   15.362725
NW                   14.064105
SC                   17.030418
SE                   14.319221
SW                   14.362778
UC                   15.545001

#questions...this is based off the monthly dataset including duplicates. Do we need to drop duplicates before completing this step? Also includes all successful and unsuccessful referrals.

### avg age at referral by county_ses

In [17]:
age_by_county_ses = referral_age[['county_ses', 'age_at_referral_in_months']]
age_by_county_ses.groupby('county_ses').mean()

              age_at_referral_in_months
county_ses
At-Risk                       13.802061
Attainment                    18.712952
Competitive                   17.196308
Distressed                    14.596003
Transitional                  14.958781

### avg age at referral by referral source

In [18]:
age_by_source = referral_age[['referral_source_type_name', 'age_at_referral_in_months']]
age_by_source.groupby('referral_source_type_name').mean()

                               age_at_referral_in_months
referral_source_type_name
CAPTA                                          18.000000
Child Care provider                            24.959620
Community/Child Find Activity                  16.587013
DCS                                             9.605556
DHS                                            15.384615
DMRS                                           18.000000
Dept. of Health                                14.969430
EIRA                                           18.781341
Early Head Start/Head Start                    23.543393
Family and Friends                             19.635108
Foster Parent                                  13.924939
Hospital                                        6.549631
LEA                                            20.400000
NHS                                             8.077626
NICU                                            2.030322
OT                                             18.304878
Other                                          13.952362
Other Health Care Provider                     14.971631
PCP                                            18.624749
PICU                                           19.500000
PT                                             16.985222
Parent                                         19.817308
Speech Therapist                               23.611285
TIPS                                           14.250000

## Count of referrals by POE

In [14]:
referrals_by_poe = monthly_df[['poe', 'referral_count']]
referrals_by_poe.groupby('poe').count()

     referral_count
poe
ET            20226
FT            11143
GN            19956
MD            17261
NW             6506
SC            14532
SE             8575
SW             6034
UC             9023

## Count of successful referrals by POE

In [15]:
success_by_poe = monthly_df[['poe', 'initial_ifsp_date']]
success_by_poe.groupby('poe').count()

     initial_ifsp_date
poe
ET                1727
FT                 793
GN                 945
MD                 699
NW                 455
SC                 934
SE                 499
SW                 528
UC                1364

In [25]:
## Percent successful by POE
percent_successful_by_poe = monthly_df[['poe', 'referral_count', 'initial_ifsp_date']]
percent_successful_by_poe = percent_successful_by_poe.groupby('poe').count()
percent_successful_by_poe['percent_successful'] = (percent_successful_by_poe['initial_ifsp_date'] / percent_successful_by_poe['referral_count']) * 100
percent_successful_by_poe

     referral_count  initial_ifsp_date  percent_successful
poe
ET            20226               1727            8.538515
FT            11143                793            7.116575
GN            19956                945            4.735418
MD            17261                699            4.049592
NW             6506                455            6.993544
SC            14532                934            6.427195
SE             8575                499            5.819242
SW             6034                528            8.750414
UC             9023               1364           15.116923