1. What is the rate of re-referral? How many children have multiple referrals (by year or by Point of Entry Office (POE))?

"what % of the total number of referrals have duplicate child IDs?" = "what % of referrals are re-referrals?"

In [6]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [7]:
compiled_monthly = pd.read_csv('../../data/Referral_Data_Compiled_Monthly.csv')

In [8]:
compiled_monthly.head()

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!

In [9]:
compiled_monthly.shape

(113256, 34)

In [10]:
compiled_monthly.columns

Index(['POE', 'Child ID', 'DOB', 'County Name', 'County SES', 'Child Phase',
       'Active', 'Service Coordinator', 'Notification/ Referral Date',
       'Parent Consent Date', 'Referral Source Type Name',
       'Initial Eligibility', 'Initial Eligibility Date', 'Initial IFSP Date',
       'Latest IFSP Date', 'Exit Reason', 'Exit Date', 'Fiscal Year',
       'Notification Month', 'Tenn Region', 'Referral Count',
       'Evaluation Count', 'Eligibility Count', 'IFSP Count',
       'Service Coordinator Counter', 'Fiscal Year.1', 'Child Count',
       '2012 Child Count', '2013 Child Count', 'third DOB', 'Late Referral',
       'Qtr', ' QTR ', 'Referral Source Category'],
      dtype='object')

In [ ]:
#len(df.index)
#df.shape[0]
"what % of referrals are re-referrals?"

In [ ]:
duplicates = compiled_monthly.duplicated(subset = ['Child ID'], keep=False)
dups_df = compiled_monthly[duplicates].sort_values(by = 'Child ID')

In [41]:
duplicates = compiled_monthly.duplicated(subset = ['Child ID'], keep='first')
dups_df = compiled_monthly[duplicates].sort_values(by = 'Child ID')

In [42]:
#this code takes the COUNT of duplicate child IDs (the # of rows in dups_df) and divides by the COUNT of all child IDs
#which gives you = "what % of the total number of referrals have duplicate child IDs?"
print(dups_df.shape[0])
print(compiled_monthly.shape[0])
dups_df.shape[0] / compiled_monthly.shape[0]

18306
113256

0.16163382072472982

In [40]:
#this shows you the unique children who have been referred more than once, there are 15,267
dups_df.drop_duplicates(subset = ['Child ID'], keep = 'first')

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
6007,ET,360966,1/18/2014,Monroe,At-Risk,Notification,I,Leslie Milligan,11/10/2016,NaN,...,1,2016,1,NaN,NaN,1/18/2017,1.0,2,Qtr 2,#REF!
6658,ET,361021,2/17/2014,Anderson,Transitional,IFSP,A,Cathy Taylor,11/29/2016,11/29/16,...,1,2016,1,NaN,NaN,2/17/2017,1.0,2,Qtr 2,#REF!
2500,GN,361038,12/25/2013,Wilson,Competitive,Eligibility,I,Mary Jane Ratliff,8/26/2016,9/2/16,...,1,2016,1,NaN,NaN,12/25/2016,NaN,1,Qtr 1,#REF!
5446,ET,361040,1/22/2014,Roane,Transitional,IFSP,A,Brandi Mohr,10/28/2016,10/28/16,...,1,2016,1,NaN,NaN,1/22/2017,1.0,2,Qtr 2,#REF!
9302,SC,363098,4/7/2014,Bedford,Transitional,IFSP,A,Tina Durham,1/31/2017,NaN,...,1,2016,1,NaN,NaN,4/7/2017,1.0,3,Qtr 3,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
111358,UC,527583,9/17/2019,Sumner,Competitive,Notification,A,Kim Correll,4/27/2022,NaN,...,1,2021,1,NaN,NaN,9/17/2022,NaN,4,Qtr 4,#REF!
111618,ET,527603,7/8/2021,Union,At-Risk,Eligibility,A,Shawnna Carpenter,5/12/2022,5/25/2022,...,1,2021,1,NaN,NaN,7/8/2024,NaN,4,Qtr 4,#REF!
111573,ET,527636,5/1/2020,Blount,Transitional,Eligibility,I,Signal Centers-EEA,5/27/2022,5/27/2022,...,1,2021,1,NaN,NaN,5/1/2023,NaN,4,Qtr 4,#REF!
112414,MD,527691,12/23/2021,Shelby,Transitional,Notification,A,Jasmine Douglass,5/20/2022,NaN,...,1,2021,1,NaN,NaN,12/23/2024,NaN,4,Qtr 4,#REF!
109913,FT,527751,10/23/2021,Sullivan,Transitional,Notification,I,Alicia Taylor - Admin,4/28/2022,NaN,...,1,2021,1,NaN,NaN,10/23/2024,NaN,4,Qtr 4,#REF!

* What is the rate of re-referral? How many children have multiple referrals (by year or by Point of Entry Office (POE))?
-15,287 children with mutiple referrals

In [21]:
#for some reason once I renamed Child ID to child_ID, it could no longer find it.
#compiled_monthly.rename(columns = {'Child ID':'child_ID', 'County Name':'county_name', 'County SES':'county_ses', 'Child Phase':'current_stage', 'Notification/ Referral Date': 'referral_date','Fiscal Year.1' : 'fiscal_year1', 'Referral Source Type Name': 'referral_source'})

,POE,boogers,DOB,county_name,county_ses,current_stage,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1,2021,1,NaN,NaN,4/7/2024,NaN,4,Qtr 4,#REF!
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,1,2021,1,NaN,NaN,3/13/2025,NaN,4,Qtr 4,#REF!
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1,2021,1,NaN,NaN,1/5/2025,NaN,4,Qtr 4,#REF!
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,1,2021,1,NaN,NaN,9/12/2023,NaN,4,Qtr 4,#REF!
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,1,2021,1,NaN,NaN,2/8/2025,NaN,4,Qtr 4,#REF!

In [22]:
#iris_df[(iris_df.sepal_length > 5) & (iris_df.sepal_length < 7)]
compiled_monthly.duplicated(subset = ['child_ID'], keep=False)

KeyError: Index(['boogers'], dtype='object')

In [15]:
compiled_monthly.duplicated(subset='Child_ID')#.value_counts() #.groupby(['Animal']).mean()

KeyError: Index(['Child_ID'], dtype='object')

In [ ]:
#schools.level.value_counts()
multiple_referrals = compiled_monthly.Child_ID.value_counts()
multiple_referrals

In [ ]:
multiple_referrals = multiple_referrals.to_frame()
type(multiple_referrals)

In [ ]:
multiple_referrals = multiple_referrals.reset_index()

In [ ]:
multiple_referrals = multiple_referrals.rename(columns = {'index':'Child_ID', 'Child_ID':'count'})
multiple_referrals

In [ ]:
#schools.query('econ_disadv > 200')
multiple_referrals = multiple_referrals.query('count > 1')
multiple_referrals

In [ ]:
compiled_monthly.columns