In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

%matplotlib inline

In [2]:
teis_mon = pd.read_csv('../data/teis_monthly.csv')
teis_mon.head( )

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!

In [3]:
teis_fy22 = pd.read_csv('../data/teis_fy22.csv')
teis_fy22.head( )

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,Referral Source Type Name,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,DCS,NaN,NaN,NaN,NaN,Unable to contact,12/29/2016
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,Parent,Ineligible,5/16/2017,NaN,NaN,Ineligible for Part C,5/16/2017
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,DCS,NaN,NaN,NaN,NaN,Parent decline,6/30/2017
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,Other,Ineligible,6/16/2017,NaN,NaN,Ineligible for Part C,6/16/2017
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,Other,Eligible,8/1/2016,8/16/2016,7/24/2018,618 - Part B eligibility not determined,9/21/2018

In [4]:
teis_mon.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 113256 entries, 0 to 113255
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   POE                          113256 non-null  object
 1   Child ID                     113256 non-null  int64
 2   DOB                          113256 non-null  object
 3   County Name                  113251 non-null  object
 4   County SES                   113251 non-null  object
 5   Child Phase                  113256 non-null  object
 6   Active                       113256 non-null  object
 7   Service Coordinator          113255 non-null  object
 8   Notification/ Referral Date  113256 non-null  object
 9   Parent Consent Date          58101 non-null   object
 10  Referral Source Type Name    113256 non-null  object
 11  Initial Eligibility          40762 non-null   object
 12  Initial Eligibility Date     40762 non-null   object
 13  Initial IFSP Date            8010 non-null    object
 14  Latest IFSP Date             7983 non-null    object
 15  Exit Reason                  39366 non-null   object
 16  Exit Date                    39366 non-null   object
 17  Fiscal Year                  113256 non-null  object
 18  Notification Month           113256 non-null  object
 19  Tenn Region                  113256 non-null  object
 20  Referral Count               113256 non-null  int64
 21  Evaluation Count             59469 non-null   float64
 22  Eligibility Count            40762 non-null   float64
 23  IFSP Count                   8010 non-null    float64
 24  Service Coordinator Counter  113256 non-null  int64
 25  Fiscal Year.1                113256 non-null  int64
 26  Child Count                  113256 non-null  int64
 27  2012 Child Count             0 non-null       float64
 28  2013 Child Count             0 non-null       float64
 29  third DOB                    113256 non-null  object
 30  Late Referral                2829 non-null    float64
 31  Qtr                          113256 non-null  int64
 32   QTR                         113256 non-null  object
 33  Referral Source Category     113256 non-null  object
dtypes: float64(6), int64(6), object(22)
memory usage: 29.4+ MB

In [5]:
teis_fy22.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 96580 entries, 0 to 96579
Data columns (total 17 columns):
 #   Column                     Non-Null Count  Dtype
---  ------                     --------------  -----
 0   POE                        96580 non-null  object
 1   Child ID                   96580 non-null  int64
 2   DOB                        96580 non-null  object
 3   County Name                96576 non-null  object
 4   County SES                 96576 non-null  object
 5   Child Phase                96580 non-null  object
 6   Active                     96580 non-null  object
 7   Service Coordinator        96579 non-null  object
 8   Notification Date          96580 non-null  object
 9   Parent Consent Date        70026 non-null  object
 10  Referral Source Type Name  96580 non-null  object
 11  Initial Eligibility        68221 non-null  object
 12  Initial Eligibility Date   68221 non-null  object
 13  Initial IFSP Date          45493 non-null  object
 14  Latest IFSP Date           44331 non-null  object
 15  Exit Reason                85194 non-null  object
 16  Exit Date                  85194 non-null  object
dtypes: int64(1), object(16)
memory usage: 12.5+ MB

In [6]:
teis_mon = teis_mon.rename(columns = {'Notification/ Referral Date' : 'Notification Date'})
teis_fy22 = teis_fy22.rename(columns = {'County SES ' : 'County SES'})

In [7]:
teis_merge = pd.merge(teis_mon, teis_fy22, how='outer')
teis_merge.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191578 entries, 0 to 191577
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   POE                          191578 non-null  object
 1   Child ID                     191578 non-null  int64
 2   DOB                          191578 non-null  object
 3   County Name                  191570 non-null  object
 4   County SES                   191570 non-null  object
 5   Child Phase                  191578 non-null  object
 6   Active                       191578 non-null  object
 7   Service Coordinator          191577 non-null  object
 8   Notification Date            191578 non-null  object
 9   Parent Consent Date          127024 non-null  object
 10  Referral Source Type Name    191578 non-null  object
 11  Initial Eligibility          107265 non-null  object
 12  Initial Eligibility Date     107265 non-null  object
 13  Initial IFSP Date            53185 non-null   object
 14  Latest IFSP Date             51996 non-null   object
 15  Exit Reason                  106768 non-null  object
 16  Exit Date                    106768 non-null  object
 17  Fiscal Year                  113256 non-null  object
 18  Notification Month           113256 non-null  object
 19  Tenn Region                  113256 non-null  object
 20  Referral Count               113256 non-null  float64
 21  Evaluation Count             59469 non-null   float64
 22  Eligibility Count            40762 non-null   float64
 23  IFSP Count                   8010 non-null    float64
 24  Service Coordinator Counter  113256 non-null  float64
 25  Fiscal Year.1                113256 non-null  float64
 26  Child Count                  113256 non-null  float64
 27  2012 Child Count             0 non-null       float64
 28  2013 Child Count             0 non-null       float64
 29  third DOB                    113256 non-null  object
 30  Late Referral                2829 non-null    float64
 31  Qtr                          113256 non-null  float64
 32   QTR                         113256 non-null  object
 33  Referral Source Category     113256 non-null  object
dtypes: float64(11), int64(1), object(22)
memory usage: 51.2+ MB

In [8]:
full_teis= pd.concat([teis_mon, teis_fy22])

In [9]:
teis_clean = full_teis[~full_teis.duplicated(['POE', 'Child ID', 'DOB', 'County Name', 'County SES', 'Child Phase',
       'Active', 'Service Coordinator', 'Notification Date',
       'Parent Consent Date', 'Referral Source Type Name',
       'Initial Eligibility', 'Initial Eligibility Date', 'Initial IFSP Date',
       'Latest IFSP Date', 'Exit Reason', 'Exit Date'])]
teis_clean.info()
#pulling out rows that are the same across all columns that the two dataframes share

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191578 entries, 0 to 96579
Data columns (total 34 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   POE                          191578 non-null  object
 1   Child ID                     191578 non-null  int64
 2   DOB                          191578 non-null  object
 3   County Name                  191570 non-null  object
 4   County SES                   191570 non-null  object
 5   Child Phase                  191578 non-null  object
 6   Active                       191578 non-null  object
 7   Service Coordinator          191577 non-null  object
 8   Notification Date            191578 non-null  object
 9   Parent Consent Date          127024 non-null  object
 10  Referral Source Type Name    191578 non-null  object
 11  Initial Eligibility          107265 non-null  object
 12  Initial Eligibility Date     107265 non-null  object
 13  Initial IFSP Date            53185 non-null   object
 14  Latest IFSP Date             51996 non-null   object
 15  Exit Reason                  106768 non-null  object
 16  Exit Date                    106768 non-null  object
 17  Fiscal Year                  113256 non-null  object
 18  Notification Month           113256 non-null  object
 19  Tenn Region                  113256 non-null  object
 20  Referral Count               113256 non-null  float64
 21  Evaluation Count             59469 non-null   float64
 22  Eligibility Count            40762 non-null   float64
 23  IFSP Count                   8010 non-null    float64
 24  Service Coordinator Counter  113256 non-null  float64
 25  Fiscal Year.1                113256 non-null  float64
 26  Child Count                  113256 non-null  float64
 27  2012 Child Count             0 non-null       float64
 28  2013 Child Count             0 non-null       float64
 29  third DOB                    113256 non-null  object
 30  Late Referral                2829 non-null    float64
 31  Qtr                          113256 non-null  float64
 32   QTR                         113256 non-null  object
 33  Referral Source Category     113256 non-null  object
dtypes: float64(11), int64(1), object(22)
memory usage: 51.2+ MB

In [10]:
import re
from tqdm.notebook import tqdm

In [11]:
for ind, row in tqdm(teis_clean.iterrows()):
    if re.search('\d{5}', str(row['Exit Date'])):
        teis_clean.loc[ind, 'Exit Date'] = np.NaN
#this is clearing out the weird data that's in the 'Exit Date' column

0it [00:00, ?it/s]

In [12]:
teis_clean[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']] = teis_clean[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']].apply(pd.to_datetime)
teis_clean

C:\Users\NSS_STUDENT\AppData\Local\Temp\ipykernel_22120\1059363929.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  teis_clean[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']] = teis_clean[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']].apply(pd.to_datetime)

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,2016-07-01,...,1.0,2016.0,1.0,NaN,NaN,2017-08-09,NaN,1.0,Qtr 1,#REF!
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,NaT,...,1.0,2016.0,1.0,NaN,NaN,2016-07-31,1.0,1.0,Qtr 1,#REF!
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,2016-07-20,...,1.0,2016.0,1.0,NaN,NaN,2019-02-05,NaN,1.0,Qtr 1,#REF!
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,2016-07-22,...,1.0,2016.0,1.0,NaN,NaN,2018-12-06,NaN,1.0,Qtr 1,#REF!
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,2016-07-18,...,1.0,2016.0,1.0,NaN,NaN,2018-04-18,NaN,1.0,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
96572,UC,523485,2019-10-23,Sumner,Competitive,IFSP,A,Miriam Espinosa,2022-03-02,2022-03-10,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
96573,UC,528430,2022-01-05,Cumberland,Transitional,IFSP,A,Lisa Davis,2022-05-10,2022-05-18,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
96574,UC,515685,2019-08-14,Sumner,Competitive,IFSP,A,Cindy Willard,2021-12-01,2021-12-07,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
96577,UC,525460,2019-08-27,Sumner,Competitive,Notification,I,Sherry Roberts-DS,2022-03-29,NaT,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN
96579,UC,514216,2021-02-04,Sumner,Competitive,IFSP,I,Dawn Reed,2021-11-05,2021-11-10,...,NaN,NaN,NaN,NaN,NaN,NaT,NaN,NaN,NaN,NaN

In [13]:
teis_clean = teis_clean.drop(columns = ['2012 Child Count', '2013 Child Count', 'Service Coordinator Counter', 'Referral Count',
                                        'Evaluation Count', 'Eligibility Count', 'IFSP Count', 'Child Count', ' QTR ', 
                                       'Referral Source Category'])
teis_clean.info ()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 191578 entries, 0 to 96579
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   POE                        191578 non-null  object
 1   Child ID                   191578 non-null  int64
 2   DOB                        191578 non-null  datetime64[ns]
 3   County Name                191570 non-null  object
 4   County SES                 191570 non-null  object
 5   Child Phase                191578 non-null  object
 6   Active                     191578 non-null  object
 7   Service Coordinator        191577 non-null  object
 8   Notification Date          191578 non-null  datetime64[ns]
 9   Parent Consent Date        127024 non-null  datetime64[ns]
 10  Referral Source Type Name  191578 non-null  object
 11  Initial Eligibility        107265 non-null  object
 12  Initial Eligibility Date   107265 non-null  object
 13  Initial IFSP Date          53185 non-null   object
 14  Latest IFSP Date           51996 non-null   object
 15  Exit Reason                106768 non-null  object
 16  Exit Date                  106523 non-null  datetime64[ns]
 17  Fiscal Year                113256 non-null  object
 18  Notification Month         113256 non-null  object
 19  Tenn Region                113256 non-null  object
 20  Fiscal Year.1              113256 non-null  float64
 21  third DOB                  113256 non-null  datetime64[ns]
 22  Late Referral              2829 non-null    float64
 23  Qtr                        113256 non-null  float64
dtypes: datetime64[ns](5), float64(3), int64(1), object(15)
memory usage: 40.6+ MB

In [14]:
all_teis_dups = teis_clean[teis_clean.duplicated(['Child ID', 'Notification Date'], keep=False)].sort_values('Child ID')
all_teis_dups
#pulling all rows that have 'Child ID' and 'Notification Date' in common to take a look

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Latest IFSP Date,Exit Reason,Exit Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
437,NW,351755,2013-11-13,Madison,Transitional,Evaluation,A,Rene Bard,2016-07-12,2016-07-12,...,NaN,NaN,NaT,2016-2017,Jul,Western,2016.0,2016-11-13,NaN,1.0
8367,NW,351755,2013-11-13,Madison,Transitional,Eligibility,I,Rene Bard,2016-07-12,2016-07-12,...,NaN,Ineligible for Part C,2016-08-25,NaN,NaN,NaN,NaN,NaT,NaN,NaN
13240,UC,353805,2013-12-04,Putnam,Transitional,IFSP,I,Anna Bolin,2016-08-05,2016-08-15,...,NaN,618 - Part B eligibility not determined,2016-12-03,NaN,NaN,NaN,NaN,NaT,NaN,NaN
1552,UC,353805,2013-12-04,Putnam,Transitional,Evaluation,A,Anna Bolin,2016-08-05,2016-08-15,...,NaN,NaN,NaT,2016-2017,Aug,Middle,2016.0,2016-12-04,NaN,1.0
4142,MD,353900,2013-10-09,Shelby,Transitional,Notification,I,JoAnn Hinkle-DA,2016-09-29,NaT,...,NaN,Referral less than 45 days,2016-09-29,2016-2017,Sep,Western,2016.0,2016-10-09,1.0,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
95952,UC,529587,2022-03-15,Sumner,Competitive,Eligibility,I,Sherry Roberts-DS,2022-05-31,2022-06-08,...,NaN,Ineligible for Part C,2022-06-24,NaN,NaN,NaN,NaN,NaT,NaN,NaN
93343,SE,529597,2020-04-10,McMinn,Transitional,Eligibility,I,Jennifer Rose - ES,2022-05-31,2022-06-04,...,NaN,Ineligible for Part C,2022-06-27,NaN,NaN,NaN,NaN,NaT,NaN,NaN
112947,SE,529597,2020-04-10,McMinn,Transitional,Notification,A,Signal Centers-EEA,2022-05-31,NaT,...,NaN,NaN,NaT,2021-2022,May,Eastern,2021.0,2023-04-10,NaN,4.0
81090,FT,529609,2020-05-13,Washington,Transitional,Notification,I,Alicia Taylor - Admin,2022-05-31,NaT,...,NaN,Unable to contact,2022-07-01,NaN,NaN,NaN,NaN,NaT,NaN,NaN
111777,FT,529609,2020-05-13,Washington,Transitional,Notification,A,Signal Centers-EEA,2022-05-31,NaT,...,NaN,NaN,NaT,2021-2022,May,Eastern,2021.0,2023-05-13,NaN,4.0

In [15]:
num_all_dup = len(np.unique(np.array(all_teis_dups['Child ID'])))
num_all_dup

76054

In [16]:
county_dups = all_teis_dups[~all_teis_dups.duplicated(['County Name', 'Child ID', 'Notification Date'], keep=False)]
county_dups
#These are instances when the same referral was noted under 2 different counties

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Latest IFSP Date,Exit Reason,Exit Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
9221,SC,360673,2014-02-19,Rutherford,Competitive,IFSP,I,LaKika King,2016-09-08,2016-09-16,...,2/6/2017,618 - Part B eligible,2017-02-18,NaN,NaN,NaN,NaN,NaT,NaN,NaN
3088,GN,360673,2014-02-19,Davidson,Competitive,Eligibility,A,Dalmys Sanchez,2016-09-08,2016-09-16,...,NaN,NaN,NaT,2016-2017,Sep,Middle,2016.0,2017-02-19,NaN,1.0
3729,ET,365886,2014-02-28,Blount,Transitional,IFSP,A,Karen Stock,2016-09-21,NaT,...,9/26/2016,NaN,NaT,2016-2017,Sep,Eastern,2016.0,2017-02-28,NaN,1.0
285,ET,365886,2014-02-28,Knox,Transitional,IFSP,I,Karen Stock,2016-09-21,2016-09-22,...,2/3/2017,618 - Part B eligibility not determined,2017-02-27,NaN,NaN,NaN,NaN,NaT,NaN,NaN
66,FT,381125,2014-09-26,Washington,Transitional,Eligibility,A,Melinda Sutton,2016-07-05,2016-07-25,...,NaN,NaN,NaT,2016-2017,Jul,Eastern,2016.0,2017-09-26,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81300,FT,528738,2021-09-22,Unicoi,At-Risk,IFSP,A,Sarah McKinney,2022-05-16,2022-05-25,...,6/27/2022,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
111795,FT,528739,2021-09-22,Washington,Transitional,Eligibility,A,Melinda Burrell,2022-05-16,2022-05-25,...,NaN,NaN,NaT,2021-2022,May,Eastern,2021.0,2024-09-22,NaN,4.0
81287,FT,528739,2021-09-22,Unicoi,At-Risk,IFSP,A,Sarah McKinney,2022-05-16,2022-05-25,...,6/27/2022,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
92411,SE,529465,2020-11-11,Bradley,Transitional,Eligibility,A,Jennifer Steward,2022-05-27,2022-05-31,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
112856,SE,529465,2020-11-11,Hamilton,Transitional,Evaluation,A,Signal Centers-EEA,2022-05-27,2022-05-31,...,NaN,NaN,NaT,2021-2022,May,Eastern,2021.0,2023-11-11,NaN,4.0

In [17]:
num_county_dup = len(np.unique(np.array(county_dups['Child ID'])))
num_county_dup

3168

In [18]:
POE_dups = all_teis_dups[~all_teis_dups.duplicated(['POE', 'Child ID', 'Notification Date'], keep=False)]
POE_dups
#These are instances when the same referral was noted under 2 different POEs

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Latest IFSP Date,Exit Reason,Exit Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
9221,SC,360673,2014-02-19,Rutherford,Competitive,IFSP,I,LaKika King,2016-09-08,2016-09-16,...,2/6/2017,618 - Part B eligible,2017-02-18,NaN,NaN,NaN,NaN,NaT,NaN,NaN
3088,GN,360673,2014-02-19,Davidson,Competitive,Eligibility,A,Dalmys Sanchez,2016-09-08,2016-09-16,...,NaN,NaN,NaT,2016-2017,Sep,Middle,2016.0,2017-02-19,NaN,1.0
769,ET,382571,2014-11-05,Sevier,Transitional,IFSP,I,Tonia Hodsden,2016-09-22,2016-09-22,...,4/11/2017,618 - Parent withdraw,2017-09-21,NaN,NaN,NaN,NaN,NaT,NaN,NaN
3810,FT,382571,2014-11-05,Cocke,Distressed,Eligibility,A,Barbara Bowman,2016-09-22,2016-09-22,...,NaN,NaN,NaT,2016-2017,Sep,Eastern,2016.0,2017-11-05,NaN,1.0
2435,SW,385467,2015-01-31,Fayette,Transitional,Eligibility,A,Yalunda Whiteside,2016-08-24,2016-09-01,...,NaN,NaN,NaT,2016-2017,Aug,Western,2016.0,2018-01-31,NaN,1.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
81455,FT,526514,2021-01-07,Hamblen,Transitional,IFSP,A,Averi Parker,2022-04-11,2022-04-27,...,5/18/2022,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
95224,UC,527542,2020-10-07,Sumner,Competitive,IFSP,A,Taylor Lee,2022-04-26,2022-05-03,...,5/11/2022,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN
110110,GN,527542,2020-10-07,Robertson,Transitional,Eligibility,A,Taylor Watson,2022-04-26,2022-05-03,...,NaN,NaN,NaT,2021-2022,Apr,Middle,2021.0,2023-10-07,NaN,4.0
111939,GN,529308,2020-06-01,Marshall,Transitional,Evaluation,A,Kim Correll,2022-05-25,2022-06-07,...,NaN,NaN,NaT,2021-2022,May,Middle,2021.0,2023-06-01,NaN,4.0
90147,SC,529308,2020-06-01,Marshall,Transitional,Eligibility,A,Kaye Curtis,2022-05-25,2022-06-07,...,NaN,NaN,NaT,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [19]:
num_POE_dup = len(np.unique(np.array(POE_dups['Child ID'])))
num_POE_dup

1240

In [20]:
county_status_dups = county_dups[county_dups.duplicated(['Child ID', 'Child Phase', 'Notification Date'], keep=False)]
county_status_dups
#looking at the duplicates that have different counties but the same status

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Latest IFSP Date,Exit Reason,Exit Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
3729,ET,365886,2014-02-28,Blount,Transitional,IFSP,A,Karen Stock,2016-09-21,NaT,...,9/26/2016,NaN,NaT,2016-2017,Sep,Eastern,2016.0,2017-02-28,NaN,1.0
285,ET,365886,2014-02-28,Knox,Transitional,IFSP,I,Karen Stock,2016-09-21,2016-09-22,...,2/3/2017,618 - Part B eligibility not determined,2017-02-27,NaN,NaN,NaN,NaN,NaT,NaN,NaN
12365,UC,385283,2015-01-31,Putnam,Transitional,IFSP,I,Kim Pierce,2017-04-25,2017-05-02,...,10/30/2017,618 - Part B eligibility not determined,2018-01-30,NaN,NaN,NaN,NaN,NaT,NaN,NaN
13302,UC,385283,2015-01-31,Overton,Transitional,IFSP,A,Kim Pierce,2017-04-25,2017-05-02,...,5/2/2017,NaN,NaT,2016-2017,Apr,Middle,2016.0,2018-01-31,NaN,4.0
12971,UC,386507,2014-10-24,Sumner,Competitive,IFSP,I,Miriam Espinosa,2016-11-01,2016-11-30,...,6/15/2017,618 - Parent withdraw,2017-09-13,NaN,NaN,NaN,NaN,NaT,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
107545,ET,523720,2021-01-05,Knox,Transitional,IFSP,A,Kristi Hopwood,2022-03-07,2022-03-08,...,4/6/2022,NaN,NaT,2021-2022,Mar,Eastern,2021.0,2024-01-05,NaN,3.0
80374,ET,524519,2021-12-28,Monroe,At-Risk,Eligibility,I,Leslie Milligan,2022-03-15,2022-03-21,...,NaN,Unable to contact,2022-05-31,NaN,NaN,NaN,NaN,NaT,NaN,NaN
109200,SE,524519,2021-12-28,Bradley,Transitional,Eligibility,A,Jaci Robertson,2022-03-15,2022-03-21,...,NaN,NaN,NaT,2021-2022,Mar,Eastern,2021.0,2024-12-28,NaN,3.0
109557,ET,526317,2021-03-21,Sevier,Transitional,Eligibility,A,Cynthia Miller,2022-04-07,2022-04-13,...,NaN,NaN,NaT,2021-2022,Apr,Eastern,2021.0,2024-03-21,NaN,4.0
80646,FT,526317,2021-03-21,Greene,At-Risk,Eligibility,I,Susan St. Lawrence,2022-04-07,2022-04-13,...,NaN,Parent decline,2022-06-03,NaN,NaN,NaN,NaN,NaT,NaN,NaN

In [21]:
teis_mon[teis_mon.duplicated(['Child ID', 'Notification Date'], keep=False)]
#reconfirming that this original dataframe doesn't have any rows that have the same Child ID and Notification Date

Empty DataFrame
Columns: [POE, Child ID, DOB, County Name, County SES, Child Phase, Active, Service Coordinator, Notification Date, Parent Consent Date, Referral Source Type Name, Initial Eligibility, Initial Eligibility Date, Initial IFSP Date, Latest IFSP Date, Exit Reason, Exit Date, Fiscal Year, Notification Month, Tenn Region, Referral Count, Evaluation Count, Eligibility Count, IFSP Count, Service Coordinator Counter, Fiscal Year.1, Child Count, 2012 Child Count, 2013 Child Count, third DOB, Late Referral, Qtr,  QTR , Referral Source Category]
Index: []

[0 rows x 34 columns]

In [22]:
teis_mon2 = teis_mon.drop(columns = ['POE', 'DOB', 'County Name', 'County SES', 'Child Phase', 'Active', 'Service Coordinator', 
                                 'Parent Consent Date', 'Referral Source Type Name', 'Initial Eligibility', 'Initial Eligibility Date', 'Initial IFSP Date', 'Latest IFSP Date', 'Exit Reason', 'Exit Date',
                                 '2012 Child Count', '2013 Child Count', 'Service Coordinator Counter', 'Referral Count', 
                                 'Evaluation Count', 'Eligibility Count', 'IFSP Count', 'Child Count', ' QTR ', 
                                 'Referral Source Category'])
teis_mon2

,Child ID,Notification Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
0,403339,7/1/2016,2016-2017,Jul,Eastern,2016,8/9/2017,NaN,1
1,404085,7/1/2016,2016-2017,Jul,Eastern,2016,7/31/2016,1.0,1
2,403623,7/1/2016,2016-2017,Jul,Eastern,2016,2/5/2019,NaN,1
3,404157,7/1/2016,2016-2017,Jul,Eastern,2016,12/6/2018,NaN,1
4,404154,7/1/2016,2016-2017,Jul,Eastern,2016,4/18/2018,NaN,1
...,...,...,...,...,...,...,...,...,...
113251,528759,5/16/2022,2021-2022,May,Middle,2021,4/7/2024,NaN,4
113252,528534,5/11/2022,2021-2022,May,Middle,2021,3/13/2025,NaN,4
113253,528430,5/10/2022,2021-2022,May,Middle,2021,1/5/2025,NaN,4
113254,528253,5/6/2022,2021-2022,May,Middle,2021,9/12/2023,NaN,4
113255,528535,5/11/2022,2021-2022,May,Middle,2021,2/8/2025,NaN,4

In [23]:
teis_merge3 = pd.merge(teis_mon2, teis_fy22, how='outer').sort_values(['Child ID'])
teis_merge3

,Child ID,Notification Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr,POE,...,Active,Service Coordinator,Parent Consent Date,Referral Source Type Name,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date
25415,104085,1/20/2018,2017-2018,Jan,Middle,2017.0,7/7/2010,1.0,3.0,GN,...,I,NaN,NaN,DCS,NaN,NaN,NaN,NaN,Unable to contact,1/25/2010
2092,350065,8/17/2016,2016-2017,Aug,Middle,2016.0,10/15/2016,1.0,1.0,UC,...,I,Steven Scarlett,NaN,PCP,NaN,NaN,NaN,NaN,Unable to contact,8/31/2016
437,351755,7/12/2016,2016-2017,Jul,Western,2016.0,11/13/2016,NaN,1.0,NW,...,I,Rene Bard,7/12/2016,Parent,Ineligible,8/25/2016,NaN,NaN,Ineligible for Part C,8/25/2016
3369,353800,9/14/2016,2016-2017,Sep,Eastern,2016.0,10/1/2016,1.0,1.0,FT,...,I,Jennifer Terranera - 45 days,NaN,Parent,NaN,NaN,NaN,NaN,Referral less than 45 days,9/15/2016
1552,353805,8/5/2016,2016-2017,Aug,Middle,2016.0,12/4/2016,NaN,1.0,UC,...,I,Anna Bolin,8/15/2016,Dept. of Health,Eligible,10/5/2016,10/10/2016,NaN,618 - Part B eligibility not determined,12/3/2016
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
114109,531592,7/1/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GN,...,A,Kim Correll,NaN,PCP,NaN,NaN,NaN,NaN,NaN,NaN
114352,531593,7/1/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GN,...,A,Kim Correll,NaN,PCP,NaN,NaN,NaN,NaN,NaN,NaN
114075,531594,7/1/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GN,...,A,Kim Correll,NaN,Other Health Care Provider,NaN,NaN,NaN,NaN,NaN,NaN
114046,531595,7/1/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,GN,...,A,Kim Correll,NaN,Hospital,NaN,NaN,NaN,NaN,NaN,NaN
114959,531596,7/1/2022,NaN,NaN,NaN,NaN,NaN,NaN,NaN,SC,...,A,Kim Correll,NaN,PCP,NaN,NaN,NaN,NaN,NaN,NaN

In [24]:
teis_merge3[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']] = teis_merge3[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']].apply(pd.to_datetime)
teis_merge3.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115524 entries, 25415 to 114959
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Child ID                   115524 non-null  int64
 1   Notification Date          115524 non-null  datetime64[ns]
 2   Fiscal Year                113256 non-null  object
 3   Notification Month         113256 non-null  object
 4   Tenn Region                113256 non-null  object
 5   Fiscal Year.1              113256 non-null  float64
 6   third DOB                  113256 non-null  datetime64[ns]
 7   Late Referral              2829 non-null    float64
 8   Qtr                        113256 non-null  float64
 9   POE                        96580 non-null   object
 10  DOB                        96580 non-null   datetime64[ns]
 11  County Name                96576 non-null   object
 12  County SES                 96576 non-null   object
 13  Child Phase                96580 non-null   object
 14  Active                     96580 non-null   object
 15  Service Coordinator        96579 non-null   object
 16  Parent Consent Date        70026 non-null   datetime64[ns]
 17  Referral Source Type Name  96580 non-null   object
 18  Initial Eligibility        68221 non-null   object
 19  Initial Eligibility Date   68221 non-null   object
 20  Initial IFSP Date          45493 non-null   object
 21  Latest IFSP Date           44331 non-null   object
 22  Exit Reason                85194 non-null   object
 23  Exit Date                  85194 non-null   datetime64[ns]
dtypes: datetime64[ns](5), float64(3), int64(1), object(15)
memory usage: 22.0+ MB

In [25]:
teis_mon3 = teis_mon.drop(columns = ['2012 Child Count', '2013 Child Count', 'Service Coordinator Counter', 'Referral Count', 
                                 'Evaluation Count', 'Eligibility Count', 'IFSP Count', 'Child Count', ' QTR ', 
                                 'Referral Source Category'])
teis_mon3

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Latest IFSP Date,Exit Reason,Exit Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,NaN,NaN,NaN,2016-2017,Jul,Eastern,2016,8/9/2017,NaN,1
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,NaN,Referral less than 45 days,7/1/2016,2016-2017,Jul,Eastern,2016,7/31/2016,1.0,1
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,NaN,NaN,NaN,2016-2017,Jul,Eastern,2016,2/5/2019,NaN,1
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,8/10/2016,NaN,NaN,2016-2017,Jul,Eastern,2016,12/6/2018,NaN,1
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,7/28/2016,NaN,NaN,2016-2017,Jul,Eastern,2016,4/18/2018,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,NaN,NaN,NaN,2021-2022,May,Middle,2021,4/7/2024,NaN,4
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,6/14/2022,NaN,NaN,2021-2022,May,Middle,2021,3/13/2025,NaN,4
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,NaN,NaN,NaN,2021-2022,May,Middle,2021,1/5/2025,NaN,4
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,5/31/2022,NaN,NaN,2021-2022,May,Middle,2021,9/12/2023,NaN,4
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,NaN,NaN,NaN,2021-2022,May,Middle,2021,2/8/2025,NaN,4

In [26]:
for ind, row in tqdm(teis_mon3.iterrows()):
    if re.search('\d{5}', str(row['Exit Date'])):
        teis_mon3.loc[ind, 'Exit Date'] = np.NaN

0it [00:00, ?it/s]

In [28]:
teis_mon3[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']] = teis_mon3[['DOB', 'Notification Date', 'Parent Consent Date', 'third DOB', 'Exit Date']].apply(pd.to_datetime)
teis_mon3

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,...,Latest IFSP Date,Exit Reason,Exit Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third DOB,Late Referral,Qtr
0,ET,403339,2014-08-09,Blount,Transitional,Eligibility,A,Kristi Borer,2016-07-01,2016-07-01,...,NaN,NaN,NaT,2016-2017,Jul,Eastern,2016,2017-08-09,NaN,1
1,FT,404085,2013-07-31,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,2016-07-01,NaT,...,NaN,Referral less than 45 days,2016-07-01,2016-2017,Jul,Eastern,2016,2016-07-31,1.0,1
2,FT,403623,2016-02-05,Sullivan,Transitional,Eligibility,A,Amy Talbert,2016-07-01,2016-07-20,...,NaN,NaN,NaT,2016-2017,Jul,Eastern,2016,2019-02-05,NaN,1
3,FT,404157,2015-12-06,Sullivan,Transitional,IFSP,A,Candice Cradic,2016-07-01,2016-07-22,...,8/10/2016,NaN,NaT,2016-2017,Jul,Eastern,2016,2018-12-06,NaN,1
4,FT,404154,2015-04-18,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,2016-07-01,2016-07-18,...,7/28/2016,NaN,NaT,2016-2017,Jul,Eastern,2016,2018-04-18,NaN,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,2021-04-07,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,2022-05-16,2022-05-26,...,NaN,NaN,NaT,2021-2022,May,Middle,2021,2024-04-07,NaN,4
113252,UC,528534,2022-03-13,Sumner,Competitive,IFSP,A,Robyn Hogan,2022-05-11,2022-05-23,...,6/14/2022,NaN,NaT,2021-2022,May,Middle,2021,2025-03-13,NaN,4
113253,UC,528430,2022-01-05,Cumberland,Transitional,Eligibility,A,Lisa Davis,2022-05-10,2022-05-18,...,NaN,NaN,NaT,2021-2022,May,Middle,2021,2025-01-05,NaN,4
113254,UC,528253,2020-09-12,Sumner,Competitive,IFSP,A,Taylor Lee,2022-05-06,2022-05-11,...,5/31/2022,NaN,NaT,2021-2022,May,Middle,2021,2023-09-12,NaN,4
113255,UC,528535,2022-02-08,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,2022-05-11,2022-05-27,...,NaN,NaN,NaT,2021-2022,May,Middle,2021,2025-02-08,NaN,4

In [29]:
teis_merge2 = pd.merge(teis_merge3, teis_mon3, on=['Child ID', 'Notification Date'], how='left')
teis_merge2.info()
##Need to do this to bring back in the data for the rows in our merge that were present only in teis_c

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115524 entries, 0 to 115523
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Child ID                     115524 non-null  int64
 1   Notification Date            115524 non-null  datetime64[ns]
 2   Fiscal Year_x                113256 non-null  object
 3   Notification Month_x         113256 non-null  object
 4   Tenn Region_x                113256 non-null  object
 5   Fiscal Year.1_x              113256 non-null  float64
 6   third DOB_x                  113256 non-null  datetime64[ns]
 7   Late Referral_x              2829 non-null    float64
 8   Qtr_x                        113256 non-null  float64
 9   POE_x                        96580 non-null   object
 10  DOB_x                        96580 non-null   datetime64[ns]
 11  County Name_x                96576 non-null   object
 12  County SES_x                 96576 non-null   object
 13  Child Phase_x                96580 non-null   object
 14  Active_x                     96580 non-null   object
 15  Service Coordinator_x        96579 non-null   object
 16  Parent Consent Date_x        70026 non-null   datetime64[ns]
 17  Referral Source Type Name_x  96580 non-null   object
 18  Initial Eligibility_x        68221 non-null   object
 19  Initial Eligibility Date_x   68221 non-null   object
 20  Initial IFSP Date_x          45493 non-null   object
 21  Latest IFSP Date_x           44331 non-null   object
 22  Exit Reason_x                85194 non-null   object
 23  Exit Date_x                  85194 non-null   datetime64[ns]
 24  POE_y                        113256 non-null  object
 25  DOB_y                        113256 non-null  datetime64[ns]
 26  County Name_y                113251 non-null  object
 27  County SES_y                 113251 non-null  object
 28  Child Phase_y                113256 non-null  object
 29  Active_y                     113256 non-null  object
 30  Service Coordinator_y        113255 non-null  object
 31  Parent Consent Date_y        58101 non-null   datetime64[ns]
 32  Referral Source Type Name_y  113256 non-null  object
 33  Initial Eligibility_y        40762 non-null   object
 34  Initial Eligibility Date_y   40762 non-null   object
 35  Initial IFSP Date_y          8010 non-null    object
 36  Latest IFSP Date_y           7983 non-null    object
 37  Exit Reason_y                39366 non-null   object
 38  Exit Date_y                  39121 non-null   datetime64[ns]
 39  Fiscal Year_y                113256 non-null  object
 40  Notification Month_y         113256 non-null  object
 41  Tenn Region_y                113256 non-null  object
 42  Fiscal Year.1_y              113256 non-null  float64
 43  third DOB_y                  113256 non-null  datetime64[ns]
 44  Late Referral_y              2829 non-null    float64
 45  Qtr_y                        113256 non-null  float64
dtypes: datetime64[ns](9), float64(6), int64(1), object(30)
memory usage: 41.4+ MB

In [30]:
teis_merge2['Referral Source Type Name_y'] = teis_merge2['Referral Source Type Name_y'].fillna(teis_merge2['Referral Source Type Name_x'])
teis_merge2['Late Referral_x'] = teis_merge2['Late Referral_x'].fillna(teis_merge2['Late Referral_y'])
teis_merge2['Qtr_x'] = teis_merge2['Qtr_x'].fillna(teis_merge2['Qtr_y'])
teis_merge2['POE_x'] = teis_merge2['POE_x'].fillna(teis_merge2['POE_y'])
teis_merge2['DOB_x'] = teis_merge2['DOB_x'].fillna(teis_merge2['DOB_y'])
teis_merge2['County Name_x'] = teis_merge2['County Name_x'].fillna(teis_merge2['County Name_y'])
teis_merge2['County SES_x'] = teis_merge2['County SES_x'].fillna(teis_merge2['County SES_y'])
teis_merge2['Child Phase_x'] = teis_merge2['Child Phase_x'].fillna(teis_merge2['Child Phase_y'])
teis_merge2['Service Coordinator_x'] = teis_merge2['Service Coordinator_x'].fillna(teis_merge2['Service Coordinator_y'])
teis_merge2['Parent Consent Date_x'] = teis_merge2['Parent Consent Date_x'].fillna(teis_merge2['Parent Consent Date_y'])
teis_merge2['Initial Eligibility_x'] = teis_merge2['Initial Eligibility_x'].fillna(teis_merge2['Initial Eligibility_y'])
teis_merge2['Initial Eligibility Date_x'] = teis_merge2['Initial Eligibility Date_x'].fillna(teis_merge2['Initial Eligibility Date_y'])
teis_merge2['Initial IFSP Date_x'] = teis_merge2['Initial IFSP Date_x'].fillna(teis_merge2['Initial IFSP Date_y'])
teis_merge2['Latest IFSP Date_x'] = teis_merge2['Latest IFSP Date_x'].fillna(teis_merge2['Latest IFSP Date_y'])
teis_merge2['Exit Reason_x'] = teis_merge2['Exit Reason_x'].fillna(teis_merge2['Exit Reason_y'])
teis_merge2['Exit Date_x'] = teis_merge2['Exit Date_x'].fillna(teis_merge2['Exit Date_x'])
teis_merge2.info()
#pulling data from the teis_c3 dataframe into the columns that originated from the teis_merge3 dataframe b

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115524 entries, 0 to 115523
Data columns (total 46 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Child ID                     115524 non-null  int64
 1   Notification Date            115524 non-null  datetime64[ns]
 2   Fiscal Year_x                113256 non-null  object
 3   Notification Month_x         113256 non-null  object
 4   Tenn Region_x                113256 non-null  object
 5   Fiscal Year.1_x              113256 non-null  float64
 6   third DOB_x                  113256 non-null  datetime64[ns]
 7   Late Referral_x              2829 non-null    float64
 8   Qtr_x                        113256 non-null  float64
 9   POE_x                        115524 non-null  object
 10  DOB_x                        115524 non-null  datetime64[ns]
 11  County Name_x                115520 non-null  object
 12  County SES_x                 115520 non-null  object
 13  Child Phase_x                115524 non-null  object
 14  Active_x                     96580 non-null   object
 15  Service Coordinator_x        115523 non-null  object
 16  Parent Consent Date_x        75365 non-null   datetime64[ns]
 17  Referral Source Type Name_x  96580 non-null   object
 18  Initial Eligibility_x        71884 non-null   object
 19  Initial Eligibility Date_x   71884 non-null   object
 20  Initial IFSP Date_x          45520 non-null   object
 21  Latest IFSP Date_x           44539 non-null   object
 22  Exit Reason_x                96177 non-null   object
 23  Exit Date_x                  85194 non-null   datetime64[ns]
 24  POE_y                        113256 non-null  object
 25  DOB_y                        113256 non-null  datetime64[ns]
 26  County Name_y                113251 non-null  object
 27  County SES_y                 113251 non-null  object
 28  Child Phase_y                113256 non-null  object
 29  Active_y                     113256 non-null  object
 30  Service Coordinator_y        113255 non-null  object
 31  Parent Consent Date_y        58101 non-null   datetime64[ns]
 32  Referral Source Type Name_y  115524 non-null  object
 33  Initial Eligibility_y        40762 non-null   object
 34  Initial Eligibility Date_y   40762 non-null   object
 35  Initial IFSP Date_y          8010 non-null    object
 36  Latest IFSP Date_y           7983 non-null    object
 37  Exit Reason_y                39366 non-null   object
 38  Exit Date_y                  39121 non-null   datetime64[ns]
 39  Fiscal Year_y                113256 non-null  object
 40  Notification Month_y         113256 non-null  object
 41  Tenn Region_y                113256 non-null  object
 42  Fiscal Year.1_y              113256 non-null  float64
 43  third DOB_y                  113256 non-null  datetime64[ns]
 44  Late Referral_y              2829 non-null    float64
 45  Qtr_y                        113256 non-null  float64
dtypes: datetime64[ns](9), float64(6), int64(1), object(30)
memory usage: 41.4+ MB

In [31]:
teis_merge2 = teis_merge2.drop(columns = ['POE_y', 'DOB_y', 'County Name_y', 'County SES_y', 'Child Phase_y', 'Active_y',
                                          'Service Coordinator_y', 'Parent Consent Date_y', 'Referral Source Type Name_x', 
                                          'Initial Eligibility_y', 'Initial Eligibility Date_y', 'Initial IFSP Date_y',
                                          'Latest IFSP Date_y', 'Exit Reason_y', 'Exit Date_y', 'Fiscal Year_y',
                                          'Notification Month_y', 'Tenn Region_y', 'Fiscal Year.1_y', 'third DOB_y', 
                                          'Late Referral_y', 'Qtr_y'])
teis_merge2.info()
#dropping the no longer needed columns now that we have the cells needed

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115524 entries, 0 to 115523
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   Child ID                     115524 non-null  int64
 1   Notification Date            115524 non-null  datetime64[ns]
 2   Fiscal Year_x                113256 non-null  object
 3   Notification Month_x         113256 non-null  object
 4   Tenn Region_x                113256 non-null  object
 5   Fiscal Year.1_x              113256 non-null  float64
 6   third DOB_x                  113256 non-null  datetime64[ns]
 7   Late Referral_x              2829 non-null    float64
 8   Qtr_x                        113256 non-null  float64
 9   POE_x                        115524 non-null  object
 10  DOB_x                        115524 non-null  datetime64[ns]
 11  County Name_x                115520 non-null  object
 12  County SES_x                 115520 non-null  object
 13  Child Phase_x                115524 non-null  object
 14  Active_x                     96580 non-null   object
 15  Service Coordinator_x        115523 non-null  object
 16  Parent Consent Date_x        75365 non-null   datetime64[ns]
 17  Initial Eligibility_x        71884 non-null   object
 18  Initial Eligibility Date_x   71884 non-null   object
 19  Initial IFSP Date_x          45520 non-null   object
 20  Latest IFSP Date_x           44539 non-null   object
 21  Exit Reason_x                96177 non-null   object
 22  Exit Date_x                  85194 non-null   datetime64[ns]
 23  Referral Source Type Name_y  115524 non-null  object
dtypes: datetime64[ns](5), float64(3), int64(1), object(15)
memory usage: 22.0+ MB

In [32]:
teis_merge2 = teis_merge2.rename(columns= {'Fiscal Year_x': 'Fiscal Year',
                                           'Notification Month_x' : 'Notification Month', 
                                           'Tenn Region_x' : 'Tenn Region', 
                                           'Fiscal Year.1_x' : 'Fiscal Year.1',
                                           'third DOB_x' : 'third_DOB',
                                           'Late Referral_x' : 'Late Referral',
                                           'Qtr_x' : 'Qtr',
                                           'POE_x' : 'POE',
                                           'DOB_x' : 'DOB',
                                           'County Name_x' : 'County Name',
                                           'County SES_x' : 'County SES',
                                           'Child Phase_x' : 'Child Phase',
                                           'Active_x' : 'Active',
                                           'Service Coordinator_x' : 'Service Coordinator',
                                           'Parent Consent Date_x' : 'Parent Consent',
                                           'Referral Source Type Name_y' : 'Referral Source Type Name',
                                           'Initial Eligibility_x' : 'Initial Eligibility',
                                           'Initial Eligibility Date_x' : 'Initial Eligibility Date',
                                           'Initial IFSP Date_x' : 'Initial IFSP Date',
                                           'Latest IFSP Date_x' : 'Latest IFSP',
                                           'Exit Reason_x' : 'Exit Reason',
                                           'Exit Date_x' : 'Exit Date'})
teis_merge2.info()
#renaming columns to get rid of the '_x'

<class 'pandas.core.frame.DataFrame'>
Int64Index: 115524 entries, 0 to 115523
Data columns (total 24 columns):
 #   Column                     Non-Null Count   Dtype
---  ------                     --------------   -----
 0   Child ID                   115524 non-null  int64
 1   Notification Date          115524 non-null  datetime64[ns]
 2   Fiscal Year                113256 non-null  object
 3   Notification Month         113256 non-null  object
 4   Tenn Region                113256 non-null  object
 5   Fiscal Year.1              113256 non-null  float64
 6   third_DOB                  113256 non-null  datetime64[ns]
 7   Late Referral              2829 non-null    float64
 8   Qtr                        113256 non-null  float64
 9   POE                        115524 non-null  object
 10  DOB                        115524 non-null  datetime64[ns]
 11  County Name                115520 non-null  object
 12  County SES                 115520 non-null  object
 13  Child Phase                115524 non-null  object
 14  Active                     96580 non-null   object
 15  Service Coordinator        115523 non-null  object
 16  Parent Consent             75365 non-null   datetime64[ns]
 17  Initial Eligibility        71884 non-null   object
 18  Initial Eligibility Date   71884 non-null   object
 19  Initial IFSP Date          45520 non-null   object
 20  Latest IFSP                44539 non-null   object
 21  Exit Reason                96177 non-null   object
 22  Exit Date                  85194 non-null   datetime64[ns]
 23  Referral Source Type Name  115524 non-null  object
dtypes: datetime64[ns](5), float64(3), int64(1), object(15)
memory usage: 22.0+ MB

In [33]:
teis_merge2['Year'] = teis_merge2['Notification Date'].dt.year
teis_merge2.head(2)

,Child ID,Notification Date,Fiscal Year,Notification Month,Tenn Region,Fiscal Year.1,third_DOB,Late Referral,Qtr,POE,...,Service Coordinator,Parent Consent,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP,Exit Reason,Exit Date,Referral Source Type Name,Year
0,104085,2018-01-20,2017-2018,Jan,Middle,2017.0,2010-07-07,1.0,3.0,GN,...,NaN,NaT,NaN,NaN,NaN,NaN,Unable to contact,2010-01-25,DCS,2018
1,350065,2016-08-17,2016-2017,Aug,Middle,2016.0,2016-10-15,1.0,1.0,UC,...,Steven Scarlett,NaT,NaN,NaN,NaN,NaN,Unable to contact,2016-08-31,PCP,2016

In [34]:
all_dups2 = teis_merge2[teis_merge2.duplicated(['Child ID', 'Notification Date'], keep=False)].sort_values('Child ID')
all_dups2
#making sure that there aren't any unanticipated duplicates

Empty DataFrame
Columns: [Child ID, Notification Date, Fiscal Year, Notification Month, Tenn Region, Fiscal Year.1, third_DOB, Late Referral, Qtr, POE, DOB, County Name, County SES, Child Phase, Active, Service Coordinator, Parent Consent, Initial Eligibility, Initial Eligibility Date, Initial IFSP Date, Latest IFSP, Exit Reason, Exit Date, Referral Source Type Name, Year]
Index: []

[0 rows x 25 columns]

Notes merging decisions 
----

After exploring the duplicate data, we decided to drop all columns from the teis_c dataframe that it shares with the teis_p dataframe except for Child ID and Notification Date. This will allow us to merge without creating any duplicates, keep the "extra" columns in teis_c, and per the folks at TEIS, the data from the teis_p dataframe should supercede any from the teis_c dataframe because it is more current