In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
%matplotlib inline

In [2]:
pulled_7_1 = pd.read_csv('../../data/Referral_Data_Pulled_7-1-22.csv')

In [3]:
pulled_7_1.head()

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification Date,Parent Consent Date,Referral Source Type Name,Initial Eligibility,Initial Eligibility Date,Initial IFSP Date,Latest IFSP Date,Exit Reason,Exit Date
0,ET,411812,12/14/2016,Blount,Transitional,Notification,I,Charity Decker,12/16/2016,NaN,DCS,NaN,NaN,NaN,NaN,Unable to contact,12/29/2016
1,ET,417398,4/6/2015,Knox,Transitional,Eligibility,I,Jackie Campbell,4/24/2017,5/2/2017,Parent,Ineligible,5/16/2017,NaN,NaN,Ineligible for Part C,5/16/2017
2,ET,419400,3/4/2016,Roane,Transitional,Notification,I,Kelly Brackney,6/6/2017,NaN,DCS,NaN,NaN,NaN,NaN,Parent decline,6/30/2017
3,ET,397571,5/11/2015,Knox,Transitional,Eligibility,I,Wendy Burton,5/24/2017,6/13/2017,Other,Ineligible,6/16/2017,NaN,NaN,Ineligible for Part C,6/16/2017
4,ET,404648,9/23/2015,Knox,Transitional,IFSP,I,Sarah Scott,7/18/2016,7/28/2016,Other,Eligible,8/1/2016,8/16/2016,7/24/2018,618 - Part B eligibility not determined,9/21/2018

In [4]:
pulled_7_1.shape

(96580, 17)

In [5]:
compiled_monthly = pd.read_csv('../../data/Referral_Data_Compiled_Monthly.csv')

In [6]:
compiled_monthly.head()

,POE,Child ID,DOB,County Name,County SES,Child Phase,Active,Service Coordinator,Notification/ Referral Date,Parent Consent Date,...,Service Coordinator Counter,Fiscal Year.1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!

In [7]:
compiled_monthly.shape

(113256, 34)

In [8]:
compiled_monthly.columns

Index(['POE', 'Child ID', 'DOB', 'County Name', 'County SES', 'Child Phase',
       'Active', 'Service Coordinator', 'Notification/ Referral Date',
       'Parent Consent Date', 'Referral Source Type Name',
       'Initial Eligibility', 'Initial Eligibility Date', 'Initial IFSP Date',
       'Latest IFSP Date', 'Exit Reason', 'Exit Date', 'Fiscal Year',
       'Notification Month', 'Tenn Region', 'Referral Count',
       'Evaluation Count', 'Eligibility Count', 'IFSP Count',
       'Service Coordinator Counter', 'Fiscal Year.1', 'Child Count',
       '2012 Child Count', '2013 Child Count', 'third DOB', 'Late Referral',
       'Qtr', ' QTR ', 'Referral Source Category'],
      dtype='object')

* What is the rate of re-referral? How many children have multiple referrals (by year or by Point of Entry Office (POE))?
-15,287 children with mutiple referrals

In [9]:
compiled_monthly.rename(columns = {'Child ID':'Child_ID', 'County Name':'county_name', 'County SES':'county_ses', 'Child Phase':'current_stage', 'Notification/ Referral Date': 'referral_date','Fiscal Year.1' : 'fiscal_year1', 'Referral Source Type Name': 'referral_source'})

,POE,Child_ID,DOB,county_name,county_ses,current_stage,Active,Service Coordinator,referral_date,Parent Consent Date,...,Service Coordinator Counter,fiscal_year1,Child Count,2012 Child Count,2013 Child Count,third DOB,Late Referral,Qtr,QTR,Referral Source Category
0,ET,403339,8/9/2014,Blount,Transitional,Eligibility,A,Kristi Borer,7/1/2016,7/1/16,...,1,2016,1,NaN,NaN,8/9/2017,NaN,1,Qtr 1,#REF!
1,FT,404085,7/31/2013,Unicoi,At-Risk,Notification,I,Jennifer Terranera - 45 days,7/1/2016,NaN,...,1,2016,1,NaN,NaN,7/31/2016,1.0,1,Qtr 1,#REF!
2,FT,403623,2/5/2016,Sullivan,Transitional,Eligibility,A,Amy Talbert,7/1/2016,7/20/16,...,1,2016,1,NaN,NaN,2/5/2019,NaN,1,Qtr 1,#REF!
3,FT,404157,12/6/2015,Sullivan,Transitional,IFSP,A,Candice Cradic,7/1/2016,7/22/16,...,1,2016,1,NaN,NaN,12/6/2018,NaN,1,Qtr 1,#REF!
4,FT,404154,4/18/2015,Hawkins,At-Risk,IFSP,A,Kathy Jeffries,7/1/2016,7/18/16,...,1,2016,1,NaN,NaN,4/18/2018,NaN,1,Qtr 1,#REF!
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
113251,UC,528759,4/7/2021,Sumner,Competitive,Evaluation,A,Sherry Roberts-DS,5/16/2022,5/26/2022,...,1,2021,1,NaN,NaN,4/7/2024,NaN,4,Qtr 4,#REF!
113252,UC,528534,3/13/2022,Sumner,Competitive,IFSP,A,Robyn Hogan,5/11/2022,5/23/2022,...,1,2021,1,NaN,NaN,3/13/2025,NaN,4,Qtr 4,#REF!
113253,UC,528430,1/5/2022,Cumberland,Transitional,Eligibility,A,Lisa Davis,5/10/2022,5/18/2022,...,1,2021,1,NaN,NaN,1/5/2025,NaN,4,Qtr 4,#REF!
113254,UC,528253,9/12/2020,Sumner,Competitive,IFSP,A,Taylor Lee,5/6/2022,5/11/2022,...,1,2021,1,NaN,NaN,9/12/2023,NaN,4,Qtr 4,#REF!
113255,UC,528535,2/8/2022,Smith,Transitional,Evaluation,A,Sherry Roberts-DS,5/11/2022,5/27/2022,...,1,2021,1,NaN,NaN,2/8/2025,NaN,4,Qtr 4,#REF!

In [16]:
#iris_df[(iris_df.sepal_length > 5) & (iris_df.sepal_length < 7)]
dups_df = compiled_monthly.duplicated(subset = 'Child_ID')
compiled_monthly[dups_df]

KeyError: Index(['Child_ID'], dtype='object')

In [ ]:
compiled_monthly.duplicated(subset='Child_ID')#.value_counts() #.groupby(['Animal']).mean()

In [ ]:
#schools.level.value_counts()
multiple_referrals = compiled_monthly.Child_ID.value_counts()
multiple_referrals

In [ ]:
multiple_referrals = multiple_referrals.to_frame()
type(multiple_referrals)

In [ ]:
multiple_referrals = multiple_referrals.reset_index()

In [ ]:
multiple_referrals = multiple_referrals.rename(columns = {'index':'Child_ID', 'Child_ID':'count'})
multiple_referrals

In [ ]:
#schools.query('econ_disadv > 200')
multiple_referrals = multiple_referrals.query('count > 1')
multiple_referrals

In [ ]:
compiled_monthly.columns